name: $(Date:yyyyMMdd)$(Rev:.r)_$(SourceBranchName)

trigger:
  branches:
    include:
    - master
    - release/*
  tags:
    include:
    - v*

jobs:
  - job: commands_zip
    displayName: "Build commands.zip"
    condition: False
    pool:
      vmImage: 'Ubuntu-18.04'
    steps:
      - script: yarn install --frozen-lockfile
        displayName: 'Yarn install'
      - script: node build_scripts/azure_release_version_check.js $(Build.SourceBranch)
        displayName: Check for tag and package.json version
      - script: yarn run package-commands-zip --version=$(git describe --tags)
        displayName: 'Run yarn package-commands-zip'
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/build_tmp'
          contents: '*.zip'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'commands build output'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: package_linux
    displayName: "Build Linux packages"
    condition: False
    pool:
      vmImage: 'Ubuntu-18.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.11.0'
      - script: yarn install --frozen-lockfile
        displayName: "yarn install"
      - script: node build_scripts/azure_release_version_check.js $(Build.SourceBranch)
        displayName: Check for tag and package.json version
      - script: yarn run electron-rebuild
        displayName: "yarn run electron-rebuild"
      - script: yarn run build
        displayName: "yarn run build"
      - script: yarn run test
        displayName: "yarn run test"
      - script: yarn run package-linux --version=$(git describe --tags)
        displayName: "yarn run package-linux"
      - script: cp $(Build.SourcesDirectory)/build_tmp/*.zip $(Build.ArtifactStagingDirectory)
      - script: cp $(Build.SourcesDirectory)/build_tmp/*.deb $(Build.ArtifactStagingDirectory)
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Linux build output'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: package_windows
    displayName: "Build Windows packages"
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - script: choco install nsis -y
        displayName: "install nsis"
      - script: choco install zip -y
        displayName: "install zip"
      - script: choco install nodejs --version=10.11.0
        displayName: "Install nodejs"
      - script: node --version
      - script: yarn --version
      - script: yarn global add node-gyp
      - script: yarn install --frozen-lockfile
        displayName: "yarn install"
      - script: node build_scripts/azure_release_version_check.js $(Build.SourceBranch)
        displayName: Check for tag and package.json version
      - script: yarn run electron-rebuild-win32
        displayName: "yarn run electron-rebuild-win32"
      - script: yarn run build
        displayName: "yarn run build"
      - script: yarn run test
        displayName: "yarn run test"
      - script: |
          PATH=C:\Program Files (x86)\NSIS\;%PATH%
          git describe --tags > APP_VERSION.txt
          set /p APP_VERSION= < APP_VERSION.txt
          del APP_VERSION.txt
          yarn run package-windows --version=%APP_VERSION%
        displayName: "yarn run package-windows"
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/build_tmp'
          contents: '*.zip'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/build_tmp'
          contents: '*.exe'
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Windows build output'
          targetPath: '$(Build.ArtifactStagingDirectory)'

  - job: package_macos
    displayName: "Build macOS packages"
    condition: False
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.11.0'
      - script: yarn install --frozen-lockfile
        displayName: "yarn install"
      - script: node build_scripts/azure_release_version_check.js $(Build.SourceBranch)
        displayName: Check for tag and package.json version
      - script: yarn run electron-rebuild
        displayName: "yarn run electron-rebuild"
      - script: yarn run build
        displayName: "yarn run build"
      - script: yarn run test
        displayName: "yarn run test"
      - script: yarn run package-macos --version=$(git describe --tags)
        displayName: "yarn run package-macos"
      - script: |
          cp $(Build.SourcesDirectory)/build_tmp/*.zip $(Build.ArtifactStagingDirectory)
          cp $(Build.SourcesDirectory)/build_tmp/*.dmg $(Build.ArtifactStagingDirectory)
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'macOS build output'
          targetPath: '$(Build.ArtifactStagingDirectory)'
